spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/catalog-service
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
